# creating arrays & add or check data types

In [2]:
# import libs 

import numpy as np
from matplotlib import pyplot as plt
from numpy import random

In [6]:
# create one dimetion array & print it out

list_1 = [1,2,3,4,5]
np_arr_1  = np.array(list_1, dtype=np.int8)
np_arr_1

array([1, 2, 3, 4, 5], dtype=int8)

In [8]:
# create multiple dimention array & print it out 

m_list_2 = [[1,2,3],[2,4,5]]
np_arr_2 = np.array(m_list_2, dtype=np.int8)
np_arr_2

array([[1, 2, 3],
       [2, 4, 5]], dtype=int8)

In [9]:
# check the array data type

np_arr_2.dtype

dtype('int8')

In [11]:
# create iterated array of range int

np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [13]:
# create random array from 0 to 5 with size 6 

np.linspace(0,5,6)

array([0., 1., 2., 3., 4., 5.])

In [19]:
# create array of zeros and ones 

np.zeros(2)

array([0., 0.])

In [20]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
np.ones(4)


array([1., 1., 1., 1.])

In [22]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [23]:
# create one dim array or randoms from of size 3

np.random.randint(5,10, 3)

array([5, 9, 7])

In [24]:
# create two dim array or randoms from of size 2,3

np.random.randint(4,10,size=(2,3))

array([[7, 4, 5],
       [5, 4, 6]])

In [25]:
# create random array of size 2 from zero to one

np.random.rand(2)


array([0.37323472, 0.95029078])

In [26]:
# create random array of size (2,3) two dim from zero to one

np.random.rand(2,3)

array([[0.77999839, 0.46478149, 0.85582146],
       [0.74620919, 0.45658316, 0.64044071]])