# slicing & indexing

In [56]:
# imports 

import numpy as np
from matplotlib import pyplot as plt
from numpy import random

In [57]:
# create array of three dim & print it out

array = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype=np.int8)
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int8)

In [58]:
# get first index in the array

array[0]

array([1, 2, 3], dtype=int8)

In [59]:
# get first item in the array of first index

array[0,0]

1

In [60]:
# set first item in the array of first inext to 100

array[0,0] = 100
array

array([[100,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9]], dtype=int8)

In [61]:
# set first item in the array of first inext to 1 again

array.itemset((0,0), 1)
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int8)

In [62]:
# get the size of the array

array.shape

(3, 3)

In [63]:
# get last item on the array 

array.item(array.shape[0] -1, array.shape[1]-1)

9

In [64]:
# get index values from the array

np.take(array,[0,1,2])



array([1, 2, 3], dtype=int8)

In [69]:
# set values by indexes in the array

np.put(array,[0,1,2], [10,10,10])
array

array([[10, 10, 10],
       [ 4,  5,  6],
       [ 7,  8,  9]], dtype=int8)

In [71]:
# slicing all array
array[ : ]

array([[10, 10, 10],
       [ 4,  5,  6],
       [ 7,  8,  9]], dtype=int8)

In [74]:
# get first index and slice the first two from the array

array[0, 0:2]

array([10, 10], dtype=int8)

In [76]:
# get even values

array[array%2==0]

array([10, 10, 10,  4,  6,  8], dtype=int8)

In [77]:
# get values greater than 5

array[array > 5]

array([10, 10, 10,  6,  7,  8,  9], dtype=int8)