# reshaping arrays

In [1]:
# import libs 

import numpy as np
from matplotlib import pyplot as plt
from numpy import random

In [5]:
# create the array

array = np.array(
    [
    [1,2,3],
    [4,5,6],
    [7,8,9]
    ] , dtype=np.int8
)
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int8)

In [11]:
# reshaping array

array.reshape((1,9))

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]], dtype=int8)

In [14]:
# resize array

np.resize(array, (2,8))

array([[1, 2, 3, 4, 5, 6, 7, 8],
       [9, 1, 2, 3, 4, 5, 6, 7]], dtype=int8)

In [15]:
# transpose & rotate array

array.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]], dtype=int8)

In [19]:
# swap & rotate array

array.swapaxes(0,1)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]], dtype=int8)

In [20]:
# convert array to one dim

array.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int8)

In [26]:
# set array unsorted values
array = np.array(
    [
    [1,2,3],
    [4,5,6],
    [7,8,9]
    ] , dtype=np.int8
)
array


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int8)

In [30]:
# sort the array

array.sort(axis=0)
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int8)